Repository FRONTENDSCHOOL10/eight-lane-highway, pull requests merged in 2024-07, with the labels that each got.

#6 feature: 로그인 페이지 구현
  README.md
  src/component/assets/buttons.scss
  src/pages/login/index.html
  src/pages/login/login.js
  src/pages/login/login.scss
  src/styles/sr-only.css
Labels: 🛟 markup, 🎀 sass, 💡 feature, ⌨️ documentation

#7 feature: 회원가입 페이지 구현
  README.md
  src/component/assets/_character.scss
  src/component/assets/_forms.scss
  src/component/assets/_inputs.scss
  src/component/assets/_layout.scss
  src/component/assets/_mixins.scss
  src/component/assets/_variables.scss
  src/component/assets/img/input-vector.svg
  src/pages/signup.html
  src/styles/reset.css
  src/styles/style.scss
Labels: 🛟 markup, 🎀 sass, 💡 feature, ⌨️ documentation

#8 feature: header 구현
  README.md
  src/component/header.html
  src/component/header/assets/address.svg
  src/component/header/assets/cart.svg
  src/component/header/assets/category.svg
  src/component/header/assets/heart.svg
  src/component/header/assets/logo.svg
  src/component/header/assets/new.svg
  src/component/header/assets/reading-glasses.svg
  src/component/header/header.css
  src/component/header/header.html
  src/component/header/header.js
  src/component/header/header.scss
Labels: 🛟 markup, 🎀 sass, 💡 feature, ⌨️ documentation

#5 feature: pop-up 마크업
  README.md
  src/component/pop-up/ assets/kurly-popup.png
  src/component/pop-up/index.html
  src/component/pop-up/main.js
  src/component/pop-up/style.scss
Labels: 💡 feature

#21 feature/header
  README.md
  src/lib/dom/attr.js
  src/lib/dom/bindEvent.js
  src/lib/dom/clearContents.js
  src/lib/dom/color.js
  src/lib/dom/css.js
  src/lib/dom/endScroll.js
  src/lib/dom/getNode.js
  src/lib/dom/index.js
  src/lib/dom/insert.js
  src/lib/dom/showAlert.js
  src/lib/dom/userList.js
  src/lib/error/index.js
  src/lib/error/refError.js
  src/lib/error/syntaxError.js
  src/lib/error/typeError.js
  src/lib/index.js
  src/lib/math/getRandom.js
  src/lib/math/index.js
  src/lib/math/toDeg.js
  src/lib/math/toRad.js
  src/lib/utils/copy.js
  src/lib/utils/delay.js
  src/lib/utils/index.js
  src/lib/utils/storage.js
  src/lib/utils/tiger.js
  src/lib/utils/type.js
  src/lib/utils/xhr.js
Labels: 💡 feature, ⌨️ documentation

#35 feature:로그인 페이지 스타일링 수정 및 로그인 js 로직 설정
  README.md
  src/component/assets/_buttons.scss
  src/component/assets/_login.scss
  src/component/assets/_mixins.scss
  src/component/assets/_variables.scss
  src/component/assets/buttons.scss
  src/component/header/header.css
  src/lib/dom/attr.js
  src/lib/dom/bindEvent.js
  src/lib/dom/clearContents.js
  src/lib/dom/color.js
  src/lib/dom/css.js
  src/lib/dom/endScroll.js
  src/lib/dom/getNode.js
  src/lib/dom/index.js
  src/lib/dom/insert.js
  src/lib/dom/showAlert.js
  src/lib/dom/userList.js
  src/lib/error/index.js
  src/lib/error/refError.js
  src/lib/error/syntaxError.js
  src/lib/error/typeError.js
  src/lib/index.js
  src/lib/math/getRandom.js
  src/lib/math/index.js
  src/lib/math/toDeg.js
  src/lib/math/toRad.js
  src/lib/utils/copy.js
  src/lib/utils/delay.js
  src/lib/utils/index.js
  src/lib/utils/storage.js
  src/lib/utils/tiger.js
  src/lib/utils/type.js
  src/lib/utils/xhr.js
  src/pages/login/index.html
  src/pages/login/login.js
  src/styles/style.scss
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement, 🛠️ javascript

#24 feature : header.js category 추가
  README.md
  src/component/assets/_header.scss
  src/component/assets/_mixins.scss
  src/component/assets/_variables.scss
  src/component/header/assets/ico_down.webp
  src/component/header/assets/index.js
  src/component/header/assets/menuImg.svg
  src/component/header/header.html
  src/component/header/header.js
  src/component/header/header.scss
  src/lib/dom/attr.js
  src/lib/dom/getNode.js
  src/lib/dom/index.js
  src/lib/index.js
  src/lib/utils/index.js
  src/lib/utils/storage.js
  src/lib/utils/tiger.js
  src/styles/style.scss
Labels: 💡 feature

#45 refactor : lib복구
  src/component/assets/_mixins.scss
Labels: 🔧bug, ⌨️ documentation

#25 feat: 기능 및 스타일수정
  README.md
  src/component/assets/popup.scss
  src/component/pop-up/assets/kurly-popup.jpg
  src/component/pop-up/assets/kurly-popup.png
  src/component/pop-up/index.html
  src/component/pop-up/main.js
  src/component/pop-up/style.scss
  src/styles/style.scss
Labels: 🛟 markup, 🎀 sass, 🚀 enhancement

#41 feature: product 컴포넌트 생성
  src/component/assets/_badges.scss
  src/component/assets/_common.scss
  src/component/assets/_products.scss
  src/component/assets/img/visual.png
  src/component/product/product.html
  src/styles/style.scss
Labels: 🛟 markup, 🎀 sass, 💡 feature

#49 refactor: 변수 이름 수정:
  src/component/assets/_login.scss
Labels: 🎀 sass, ⌨️ documentation

#50 refactor : lib 추가
  src/lib/dom/attr.js
  src/lib/dom/bindEvent.js
  src/lib/dom/clearContents.js
  src/lib/dom/css.js
  src/lib/dom/getNode.js
  src/lib/dom/index.js
  src/lib/dom/insert.js
  src/lib/index.js
  src/lib/utils/tiger.js
  src/lib/utils/type.js
Labels: 💡 feature, ⌨️ documentation

#55 refactor : lib 추가
  README.md
Labels: 💡 feature

#56 refactor : mixin 수정
  src/component/assets/_mixins.scss
Labels: 🚀 enhancement, ⌨️ documentation

#33 feature: 회원가입 마크업 및 스크립트 작업
  .github/PULL_REQUEST_TEMPLATE.md
  src/component/assets/_buttons.scss
  src/component/assets/_forms.scss
  src/component/assets/_header.scss
  src/component/assets/_inputs.scss
  src/component/assets/_layout.scss
  src/component/assets/_mixins.scss
  src/component/assets/_variables.scss
  src/pages/signup.html
  src/pages/signup/checkAll.js
  src/pages/signup/index.html
  src/pages/signup/signup.js
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement, 🛠️ javascript

#59 refactor : header.scss mixin 수정
  src/component/assets/_header.scss
Labels: 🚀 enhancement

#63 refactor : variables.scss
  src/component/assets/_header.scss
  src/component/assets/_variables.scss
Labels: 🚀 enhancement

#62 refactor: input width 값 수정
  README.md
  src/component/assets/_inputs.scss
Labels: 🚀 enhancement

#71 refactor : class명 수정
  src/component/assets/_recentproduct.scss
  src/component/recent-product/index.html
Labels: 🔧bug

#69 feat : recentproduct 복구
  README.md
  src/component/assets/_recentproduct.scss
  src/component/recent-product/assets/below.svg
  src/component/recent-product/assets/upper.svg
  src/component/recent-product/main.js
  src/styles/style.scss
Labels: 🔧bug

#73 feature: 상품 한개 노출 컴포넌트 작업
  README.md
  src/component/assets/_badges.scss
  src/component/assets/_buttons.scss
  src/component/assets/_character.scss
  src/component/assets/_products.scss
  src/component/assets/_variables.scss
  src/component/product/product.html
Labels: 🛟 markup, 🎀 sass, 💡 feature, ⚙️ pocketbase

#65 feat : 클래스 토글로 기능 수정
  README.md
  src/component/assets/_popup.scss
  src/component/pop-up/index.html
  src/component/pop-up/main.js
Labels: 🚀 enhancement

#67 feat: 로그인 정보 저장
  README.md
  src/component/assets/_login.scss
  src/pages/login/login.js
Labels: 🎀 sass, 💡 feature, 🚀 enhancement, 🛠️ javascript

#75 feat : header 마크업 및 이벤트 추가 그리드 레이아웃
  README.md
  src/component/assets/_header.scss
  src/component/header/header.js
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement, 🛠️ javascript

#82 doc: 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/기본-이슈-템플릿.md
  README.md
Labels: ⌨️ documentation

#86 feat : 데이터베이스 관련 API 생성
  README.md
  src/api/getPbImageURL.js
  src/api/pocketbase.js
Labels: 💡 feature

#88 feat : getPbImageURL 수정
  src/api/getPbImageURL.js
Labels: 🚀 enhancement

#77 feat: add-shopping-basket_01 장바구니 컴포넌트 마크업 및 스타일링
  README.md
  src/component/addShoppingBasket/addShoppingBasket.html
  src/component/addShoppingBasket/addShoppingBasket.js
  src/component/assets/_addShoppingBasket.scss
  src/component/assets/_buttons.scss
  src/component/assets/_mixins.scss
  src/component/assets/img/minus-button-black.svg
  src/component/assets/img/plus-button-black.svg
  src/styles/style.scss
Labels: 🛟 markup, 🎀 sass, 💡 feature, ⌨️ documentation

#74 feat : 마크업 및 스타일링 수정
  README.md
  src/component/assets/_recentproduct.scss
  src/component/recent-product/index.html
  src/component/recent-product/main.js
Labels: 🛟 markup, 🎀 sass, 💡 feature

#93 refactor: vite 배포 관련 파일 수정
  README.md
  src/component/product/product-info.html
  src/component/product/product.html
  src/pages/page.html
  src/pages/register/checkAll.js
  src/pages/register/index.html
  src/pages/register/register.js
Labels: 🚀 enhancement

#95 feat: 상품 상세 페이지 초기 마크업 및 빌드를 위한 일부 코드 수정
  package-lock.json
  src/component/addShoppingBasket/addShoppingBasket.html
  src/component/assets/_products-detail.scss
  src/component/product/product-detail.html
  src/lib/utils/storage.js
  src/lib/utils/tiger.js
  src/styles/style.scss
  vite.config.js
Labels: 🛟 markup, 🔧bug, 🚀 enhancement

#98 feat: 제품 세부 정보 하단 마크업과 스타일링
  README.md
  src/component/assets/_products-detail.scss
  src/component/assets/_variables.scss
  src/component/product/product-detail.html
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement, ⌨️ documentation

#103 feat : 스와이퍼 기능 추가
  README.md
  src/component/assets/_recentproduct.scss
  src/component/recent-product/index.html
  src/component/recent-product/main.js
Labels: 💡 feature

#104 feat : product slide swiper 구현
  package-lock.json
  package.json
  src/component/assets/_badges.scss
  src/component/assets/_character.scss
  src/component/assets/_footer.scss
  src/component/assets/_header.scss
  src/component/assets/_mixins.scss
  src/component/assets/_product-slide.scss
  src/component/assets/_products.scss
  src/component/assets/img/next-button-black.svg
  src/component/footer/footer.js
  src/component/header/header.js
  src/component/product/product-slide.html
  src/component/product/product-slide.js
  src/component/product/product.html
  src/styles/style.scss
  vite.config.js.timestamp-1720514974785-1cdf0bd91d479.mjs
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement, ⌨️ documentation, 🛠️ javascript

#80 feat: 상세페이지 상단 정보 부분 마크업
  README.md
  src/component/assets/_buttons.scss
  src/component/assets/_products.scss
  src/component/assets/_typography.scss
  src/component/assets/_variables.scss
  src/component/assets/img/icon-bell.svg
  src/component/assets/img/icon-heart.svg
  src/component/product/product-info.html
  src/styles/style.scss
Labels: 🛟 markup, 🎀 sass, 💡 feature

#106 refactor : 이미지 경로수정
  docs/assets/css-azFYDAD8.js
  docs/assets/header-Gk-s0h6z.js
  docs/assets/insta-2y8yXE_1.svg
  docs/assets/login-0xzVABxG.css
  docs/assets/login-AplK8av2.js
  docs/assets/logo-B8EPEGVT.svg
  docs/assets/modulepreload-polyfill-9p4a8sJU.js
  docs/assets/pocketbase.es-knC2my0u.js
  docs/assets/popup-rC9owpRD.js
  docs/assets/recentproduct-xDEKPi7K.js
  docs/assets/reset-0zi2r23m.css
  docs/assets/style-kmjPQDb_.css
  docs/assets/type-ux6Gv8tB.js
  docs/images/address.svg
  docs/images/below.svg
  docs/images/cart.svg
  docs/images/category.svg
  docs/images/heart.svg
  docs/images/ico_down.webp
  docs/images/input-vector.svg
  docs/images/kurly-popup.jpg
  docs/images/logo.svg
  docs/images/menuImg.svg
  docs/images/minus-button-black.svg
  docs/images/new.svg
  docs/images/plus-button-black.svg
  docs/images/reading-glasses.svg
  docs/images/upper.svg
  docs/images/visual.png
  docs/index.html
  docs/src/component/addShoppingBasket/addShoppingBasket.html
  docs/src/component/header/header.html
  docs/src/component/pop-up/index.html
  docs/src/component/product/product-detail.html
  docs/src/component/product/product-info.html
  docs/src/component/product/product.html
  docs/src/component/recent-product/index.html
  docs/src/pages/login/index.html
  docs/src/pages/register/index.html
  docs/vite.svg
  src/component/assets/_popup.scss
  src/component/recent-product/index.html
Labels: 🔧bug, ⌨️ documentation

#114 feat : cart 기본 마크업
  README.md
  public/images/frozen.svg
  public/images/sun.svg
  public/images/water.svg
  src/component/assets/_typography.scss
  src/pages/cart/index.html
  src/styles/style.scss
Labels: 🛟 markup

#113 feat: 상품 정보란 스타일링 작업
  README.md
  index.html
  public/images/icon-bell.svg
  public/images/icon-heart.svg
  public/images/icon-minus-active.svg
  public/images/icon-minus-disabled.svg
  public/images/icon-plus-active.svg
  public/images/icon-plus-disabled.svg
  src/component/assets/_badges.scss
  src/component/assets/_buttons.scss
  src/component/assets/_mixins.scss
  src/component/assets/_products.scss
  src/component/assets/_typography.scss
  src/component/product/product-info.html
  src/styles/reset.css
  vite.config.js.timestamp-1720514974785-1cdf0bd91d479.mjs
Labels: 🛟 markup, 🎀 sass, 🚀 enhancement

#111 feat : product slide 구현
  README.md
  package-lock.json
  public/images/next-button-black.svg
  src/component/assets/_footer.scss
  src/component/assets/_header.scss
  src/component/assets/_products-slide.scss
  src/component/assets/_products.scss
  src/component/assets/_typography.scss
  src/component/assets/_variables.scss
  src/component/footer/footer.html
  src/component/footer/footer.js
  src/component/header/header.html
  src/component/header/header.js
  src/component/product/product-slide.html
  src/component/product/product-slide.js
  src/component/product/product.html
  vite.config.js
Labels: 💡 feature, ⚙️ pocketbase, 🛠️ javascript

#117 feat : 장바구니 기본 스타일링
  src/component/assets/_cart.scss
  src/component/assets/_typography.scss
Labels: 🎀 sass

#118 bug: 배포 yml 오류 - 빌드 후 나머지 파일 추가
  docs/assets/css-azFYDAD8.js
  docs/assets/footer-sdE6Eert.js
  docs/assets/header-gvOGYooM.js
  docs/assets/login-TT_3esKV.js
  docs/assets/modulepreload-polyfill-9p4a8sJU.js
  docs/assets/pocketbase.es-knC2my0u.js
  docs/assets/popup-GLkvY8bH.js
  docs/assets/recentproduct-w2zOIOpM.js
  docs/assets/reset-MgWYvZRs.css
  docs/assets/sr-only-0xzVABxG.css
  docs/assets/style-Y7sHKK8f.js
  docs/assets/style-vaYluf6e.css
  docs/assets/type-ux6Gv8tB.js
  docs/favicon.ico
  docs/images/address.svg
  docs/images/below.svg
  docs/images/blog.svg
  docs/images/cart.svg
  docs/images/category.svg
  docs/images/facebook.svg
  docs/images/frozen.svg
  docs/images/heart.svg
  docs/images/ico_down.webp
  docs/images/icon-bell.svg
  docs/images/icon-heart.svg
  docs/images/icon-minus-active.svg
  docs/images/icon-minus-disabled.svg
  docs/images/icon-plus-active.svg
  docs/images/icon-plus-disabled.svg
  docs/images/input-vector.svg
  docs/images/insta.svg
  docs/images/kurly-popup.jpg
  docs/images/logo.svg
  docs/images/menuImg.svg
  docs/images/minus-button-black.svg
  docs/images/new.svg
  docs/images/next-button-black.svg
  docs/images/plus-button-black.svg
  docs/images/post.svg
  docs/images/privacy.svg
  docs/images/reading-glasses.svg
  docs/images/security.svg
  docs/images/sun.svg
  docs/images/tossPayments.svg
  docs/images/upper.svg
  docs/images/visual.png
  docs/images/water.svg
  docs/images/wooriBank.svg
  docs/images/youtube.svg
  docs/index.html
  docs/src/component/addShoppingBasket/addShoppingBasket.html
  docs/src/component/footer/footer.html
  docs/src/component/header/header.html
  docs/src/component/pop-up/index.html
  docs/src/component/product/product-detail.html
  docs/src/component/product/product-info.html
  docs/src/component/product/product.html
  docs/src/component/recent-product/index.html
  docs/src/pages/login/index.html
  docs/src/pages/register/index.html
Labels: 🔧bug

#119 fix: 배포 ^^ 문제
  .github/workflows/main.yml
  index.html
  src/component/addShoppingBasket/addShoppingBasket.html
  src/component/assets/_banner.scss
  src/component/assets/_reset.scss
  src/component/assets/_sr-only.scss
  src/component/banner/banner.html
  src/component/banner/banner.js
  src/component/footer/footer.html
  src/component/footer/footer.js
  src/component/header/header.js
  src/component/pop-up/index.html
  src/component/product/product-detail.html
  src/component/product/product-info.html
  src/component/product/product-slide.html
  src/component/product/product.html
  src/component/recent-product/index.html
  src/pages/cart/index.html
  src/pages/login/index.html
  src/pages/register/index.html
  src/styles/style.scss
  vite.config.js
Labels: 🔧bug

#110 feat: 상품 세부 정보 하단 추가 마크업 및 스타일링
  package.json
  public/images/checkpoint.png
  public/images/icon-check-list.svg
  public/images/icon-k-box.svg
  public/images/icon-recycle.svg
  public/images/icon-truck.svg
  public/images/icon-won.svg
  public/images/jjolmeon-detail-info.png
  public/images/jjolmeon.png
  src/component/addShoppingBasket/addShoppingBasket.html
  src/component/assets/_products-detail.scss
  src/component/product/product-detail.html
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement

#122 feat : 장바구니 기본 스타일링
  src/component/assets/_cart.scss
  src/pages/cart/index.html
Labels: 🛟 markup, 🎀 sass

#121 feat :product slide 스와이퍼 구현 및 pb활용한 동적으로 제품 추가
  public/images/icon-down.svg
  src/component/assets/_footer.scss
  src/component/assets/_header.scss
  src/component/assets/_products-slide.scss
  src/component/assets/_products.scss
  src/component/footer/footer.js
  src/component/header/header.js
  src/component/product/product-slide.html
  src/component/product/product-slide.js
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement, ⚙️ pocketbase, 🛠️ javascript

#128 feat: 회원가입 스타일링 디테일
  src/component/assets/_buttons.scss
  src/component/assets/_register.scss
  src/component/assets/_reset.scss
  src/pages/register/index.html
  src/styles/style.scss
Labels: 🎀 sass, 🚀 enhancement

#129 feat : header,footer 이미지 경로 변경 및 마크업 수정
  public/images/blog.svg
  public/images/facebook.svg
  public/images/icon-footer.png
  public/images/icon-header.png
  public/images/insta.svg
  public/images/post.svg
  public/images/privacy.svg
  public/images/security.svg
  public/images/tossPayments.svg
  public/images/wooriBank.svg
  public/images/youtube.svg
  src/component/assets/_footer.scss
  src/component/assets/_header.scss
  src/component/footer/footer.js
  src/component/header/header.js
  src/component/product/product-slide.html
  src/component/product/product-slide.js
Labels: 🚀 enhancement, ⌨️ documentation

#131 feat: 제품 세부 하단 와이 칼리 부분 마크업 변경 및 부분 스타일링
  src/component/assets/_mixins.scss
  src/component/assets/_products-detail.scss
  src/component/product/product-detail.html
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement

#123 feat: banner 구현
  index.html
  src/component/assets/_banner.scss
  src/component/banner/banner.html
  src/component/banner/banner.js
  vite.config.js
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🛠️ javascript

#135 feat : 장바구니 체크박스 스타일링
  README.md
  public/images/cancel.svg
  public/images/input-checked.svg
  public/images/input-unchecked.svg
  src/component/assets/_cart.scss
  src/component/assets/_popup.scss
  src/lib/utils/index.js
  src/lib/utils/price.js
  src/pages/cart/index.html
  src/pages/cart/main.js
  vite.config.js
Labels: 🛟 markup, 🎀 sass

#137 feat : 버튼 활성화 및 기능 추가
  src/component/assets/_recentproduct.scss
  src/component/recent-product/index.html
  src/component/recent-product/main.js
Labels: 🎀 sass, 💡 feature, 🚀 enhancement

#143 feat :header, product-slide 수정
  src/component/assets/_header.scss
  src/component/header/header.html
  src/component/header/header.js
  src/component/product/product-slide.js
  src/component/product/product.html
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement

#142 feat: 회원가입 스타일링 수정 및 기능 구현
  README.md
  public/images/icon-arrow.svg
  src/component/assets/_buttons.scss
  src/component/assets/_forms.scss
  src/component/assets/_inputs.scss
  src/component/assets/_register.scss
  src/component/assets/_reset.scss
  src/component/assets/_typography.scss
  src/pages/register/checkAll.js
  src/pages/register/index.html
  src/pages/register/register.js
  src/pages/register/userAddress.js
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement, 🛠️ javascript

#133 feat: 제품 상세 페이지 마크업 및 스타일링 마무리
  README.md
  src/component/assets/_products-detail.scss
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement, ⌨️ documentation

#149 feat: 회원가입 기능 구현
  README.md
  src/component/assets/_register.scss
  src/pages/register/emailCheck.js
  src/pages/register/idCheck.js
  src/pages/register/index.html
  src/pages/register/passwordCheck.js
  src/pages/register/register.js
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement, ⚙️ pocketbase, 🛠️ javascript

#145 feat : 전체선택 체크박스 관련 기능구현
  index.html
  src/component/assets/_cart.scss
  src/pages/cart/index.html
  src/pages/cart/main.js
Labels: 💡 feature

#146 feat: 장바구니 추가 기능 구현 마무리
  README.md
  src/component/addShoppingBasket/addShoppingBasket.html
  src/component/addShoppingBasket/addShoppingBasket.js
  src/component/assets/_addShoppingBasket.scss
Labels: 🎀 sass, 💡 feature, 🚀 enhancement, ⌨️ documentation, 🛠️ javascript

#148 feat: 상품 상세 보기 페이지 추가
  index.html
  src/pages/product-detail/product-detail.html
  src/pages/register/index.html
  src/pages/register/register.js
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🔧bug, 🚀 enhancement, 🏳️ question

#157 feat: 장바구니 추가 새 항목 추가 시 추가되도록 변경
  src/component/addShoppingBasket/addShoppingBasket.js
Labels: 🚀 enhancement, 🛠️ javascript

#158 feat : footer.js / banner.js 기능 추가
  index.html
  main.js
  public/images/next-button-white.svg
  src/component/assets/_banner.scss
  src/component/assets/_footer.scss
  src/component/assets/_header.scss
  src/component/assets/_layout.scss
  src/component/assets/_products-slide.scss
  src/component/banner/banner.html
  src/component/banner/banner.js
  src/component/footer/footer.js
  src/component/product/product-slide.js
  src/component/product/product-slide2.js
  src/styles/style.scss
Labels: 💡 feature, 🚀 enhancement, 🛠️ javascript

#160 feat: 상품 후기 게시판 추가
  README.md
  public/images/icon-arrow-left.svg
  public/images/icon-arrow-right.svg
  src/component/assets/_badges.scss
  src/component/assets/_buttons.scss
  src/component/assets/_products.scss
  src/component/assets/_variables.scss
  src/component/product/product-info.html
  src/component/product/product-slide.js
  src/component/product/product-slide2.js
  src/pages/product/product-detail.html
  src/pages/product/product-detail.js
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement

#164 bug: API 미작동 이슈 수정
  src/pages/register/index.html
Labels: 🔧bug, 🛠️ javascript

#156 feat : 장바구니 로컬스토리지 관련 기능 구현
  README.md
  index.html
  src/component/assets/_cart.scss
  src/pages/cart/countedItem.js
  src/pages/cart/delete.js
  src/pages/cart/index.html
  src/pages/cart/main.js
  src/pages/cart/selectAll.js
  src/pages/cart/sumAllPrice.js
  src/pages/cart/syncCheckBox.js
  src/pages/cart/updatePrice.js
Labels: 💡 feature, 🚀 enhancement, ⚙️ pocketbase

#169 refactor: product-slide삭제 및 product-slide2 수정
  src/component/product/product-slide.js
  src/component/product/product-slide2.js
Labels: 🚀 enhancement

#170 feat: 로그인 페이지 헤더 푸터와 결합
  src/component/accodion/accodion.html
  src/component/accodion/accodion.js
  src/component/assets/_accodion.scss
  src/component/assets/_login.scss
  src/pages/login/index.html
  src/pages/login/login.js
  src/styles/style.scss
Labels: 🛟 markup, 🚀 enhancement, 🛠️ javascript

#172 feat : 스크립트 경로 수정
  main.js
  src/pages/cart/main.js
Labels: 🔧bug, 🚀 enhancement, 🛠️ javascript

#174 refactor: 아코디언 선택 클래스 수정
  src/component/accodion/accodion.js
  src/component/assets/_accodion.scss
Labels: 🎀 sass, 🔧bug, 🛠️ javascript

#177 feat : 회원가입 페이지 합치기
  src/component/assets/_cart.scss
  src/component/assets/_register.scss
  src/pages/register/index.html
  src/pages/register/register.js
Labels: 🛟 markup, 🎀 sass, 🚀 enhancement

#181 feat: 상품 리스트 페이지 마크업 및 스타일링과 데이터 받아오기
  src/component/assets/_product-list.scss
  src/component/assets/_products.scss
  src/pages/productList/index.html
  src/pages/productList/productList.js
  src/styles/style.scss
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🛠️ javascript

#180 feat: 상품 상세페이지 데이터 오류 해결
  package-lock.json
  package.json
  src/component/assets/_products.scss
  src/component/product/product-slide1.js
  src/pages/product/product-detail.html
  src/pages/product/product-detail.js
Labels: 🔧bug

#184 feat: 제품 리스트 페이지 마크업 및 스타일링 마무리(페이지네이션 제외)
  src/component/assets/_product-list.scss
  src/pages/productList/index.html
  src/pages/productList/productList.js
  vite.config.js
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement

#179 refactor : swiper 생성자 함수로 구현 및 product-silde로 합치기
  index.html
  main.js
  src/component/assets/_header.scss
  src/component/assets/_popup.scss
  src/component/header/header.js
  src/component/product/product-slide.html
  src/component/product/product-slide.js
  src/component/product/product-slide2.js
  src/component/recent-product/main.js
Labels: 🔧bug, 🚀 enhancement, 🛠️ javascript, 🕯️ discussion

#182 feat : pagination 컴포넌트 구현
  public/images/pagination-sprite.png
  src/component/assets/_pagination.scss
  src/component/pagination/index.html
  src/styles/style.scss
Labels: 🛟 markup, 🎀 sass, 💡 feature

#191 bug: 없는 변수 호출 오류로 인한 디버깅
  README.md
  index.html
  src/component/assets/_products.scss
  src/component/pop-up/main.js
  src/component/product/product-slide.js
  src/component/product/product-slide2.js
  src/component/recent-product/main.js
  src/pages/product/product-detail.js
Labels: 🔧bug, 🚀 enhancement, 🛠️ javascript

#189 feat : 이메일 유효성 인풋박스 반영
  src/component/assets/_inputs.scss
  src/component/assets/_variables.scss
  src/pages/register/emailCheck.js
Labels: 🎀 sass, 🚀 enhancement

#192 feat : main product-slide 수정
  src/component/assets/_footer.scss
  src/component/assets/_header.scss
  src/component/header/header.js
  src/component/product/product-slide.js
  src/component/recent-product/main.js
Labels: 🔧bug, 🚀 enhancement, 🛠️ javascript

#195 feat : 선택수량 및 전체수량 반영 동기화
  README.md
  src/component/assets/_cart.scss
  src/pages/cart/countedItem.js
  src/pages/cart/delete.js
  src/pages/cart/index.html
  src/pages/cart/main.js
  src/pages/cart/sumAllPrice.js
  src/pages/cart/updatePrice.js
Labels: 🛟 markup, 🔧bug, 🚀 enhancement

#198 feat: 회원가입 스타일링 수정 및 주소 기능 추가
  src/component/assets/_inputs.scss
  src/component/assets/_register.scss
  src/component/assets/_variables.scss
  src/component/product/product-slide.js
  src/pages/register/emailCheck.js
  src/pages/register/idCheck.js
  src/pages/register/index.html
  src/pages/register/nameCheck.js
  src/pages/register/passwordCheck.js
  src/pages/register/register.js
  src/pages/register/userAddress.js
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🔧bug, 🚀 enhancement, 🛠️ javascript

#196 feat: 상품 리스트 js 기능 중 상품 개수 세는 함수 구현
  README.md
  src/component/accodion/accodion.js
  src/component/accodion/countAccodionItems.js
  src/component/assets/_product-list.scss
  src/pages/productList/index.html
  src/pages/productList/productList.js
Labels: 🛟 markup, 💡 feature, 🚀 enhancement, ⌨️ documentation, 🛠️ javascript

#200 feat : header signup-> register로 변경 및 코드 웹 표준 검사
  index.html
  src/component/assets/_header.scss
  src/component/header/header.js
Labels: 🚀 enhancement, 🛠️ javascript

#203 refactor : product-slide
  src/component/product/product-slide.js
Labels: 🔧bug

#205 feat: 상품 상세페이지 스크립트 마무리
  src/component/assets/_cart.scss
  src/pages/cart/main.js
  src/pages/product/product-detail.html
  src/pages/product/productCount.js
  src/pages/product/productDetail.js
Labels: 💡 feature, 🚀 enhancement, 🛠️ javascript

#207 feat: 상품 리스트 페이지네이션 기능 구현
  src/component/accodion/countAccodionItems.js
  src/component/assets/_product-list.scss
  src/pages/productList/index.html
  src/pages/productList/productList.js
Labels: 🎀 sass, 💡 feature, 🚀 enhancement, 🛠️ javascript

#208 feat : product-slide.js/recent-product
  README.md
  index.html
  main.js
  src/component/assets/_footer.scss
  src/component/assets/_header.scss
  src/component/assets/_popup.scss
  src/component/assets/_products.scss
  src/component/assets/_topBanner.scss
  src/component/product/product-slide.js
  src/component/recent-product/main.js
  src/component/topBanner/index.html
  src/component/topBanner/topBanner.js
  src/styles/style.scss
Labels: 💡 feature, 🚀 enhancement, 🛠️ javascript

#213 feat: 뱃지 스타일 추가
  src/component/assets/_badges.scss
Labels: 🎀 sass, 🚀 enhancement

#217 feat : product-slide 디버깅 및 기능개선
  src/component/assets/_header.scss
  src/component/assets/_products.scss
  src/component/cancel/cancel.js
  src/component/cancel/index.html
  src/component/header/header.js
  src/component/product/product-slide.js
Labels: 🔧bug, 🚀 enhancement

#212 feat : 장바구니 디버깅 및 기능 개선
  src/component/assets/_cart.scss
  src/pages/cart/countedItem.js
  src/pages/cart/delete.js
  src/pages/cart/hidePrice.js
  src/pages/cart/index.html
  src/pages/cart/main.js
Labels: 💡 feature, 🔧bug, 🚀 enhancement

#219 feat: 장바구니 추가 팝업 일부 수정과 상품리스트와 팝업 서로 연결
  README.md
  src/component/addShoppingBasket/addShoppingBasket.js
  src/component/assets/_addShoppingBasket.scss
  src/component/assets/_product-list.scss
  src/pages/productList/index.html
  src/pages/productList/productList.js
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🚀 enhancement, 🛠️ javascript

#220 feat: 회원가입 리로드 페이지 지정
  src/pages/register/index.html
  src/pages/register/register.js
Labels: 🚀 enhancement

#215 feat: 마이페이지 추가
  public/images/background-title.png
  public/images/icon-coupon.svg
  public/images/icon-like-heart.svg
  public/images/icon-order-list.svg
  public/images/icon-product-qna.svg
  src/component/assets/_mypage.scss
  src/component/assets/_typography.scss
  src/component/assets/_variables.scss
  src/pages/member/mypage.html
  src/pages/member/mypage.js
  src/pages/register/index.html
  src/styles/style.scss
  vite.config.js
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🛠️ javascript

#210 feat: 상품 문의 & 상품 후기 스타일링
  README.md
  src/component/assets/_inputs.scss
  src/component/assets/_products-detail.scss
  src/component/assets/_products.scss
  src/component/assets/_typography.scss
  src/pages/product/addToCartBubble.js
  src/pages/product/product-detail.html
  src/pages/product/productCount.js
  src/pages/product/productDetail.js
  src/pages/product/productScroll.js
Labels: 🎀 sass, 🚀 enhancement

#223 refactor : header input hover 컬러 변경 및 readme 업데이트
  README.md
  src/component/assets/_header.scss
  vite.config.js.timestamp-1721216523966-e6336ae837859.mjs
Labels: 🚀 enhancement, ⌨️ documentation

#227 refactor : 장바구니 디버깅 및 리팩토링
  README.md
  src/component/assets/_badges.scss
  src/component/assets/_cart.scss
  src/pages/cart/countedItem.js
  src/pages/cart/delete.js
  src/pages/cart/hidePrice.js
  src/pages/cart/index.html
  src/pages/cart/selectAll.js
  src/pages/cart/sumAllPrice.js
Labels: 🎀 sass, 🔧bug, 🚀 enhancement, 🛠️ javascript

#225 bug: 포켓베이스 API에서 axios로 변경
  src/pages/register/index.html
  src/pages/register/register.js
Labels: 🔧bug

#230 feat : 회원탈퇴 기능 구현
  src/component/cancel/cancel.js
  src/component/header/header.js
  src/component/product/product-slide.js
  src/pages/member/mypage.html
  src/pages/member/mypage.js
Labels: 💡 feature

#231 feat: 필터 제작(미완)
  src/component/accodion/accodion.js
  src/pages/productList/index.html
Labels: 🛟 markup

#235 feat: 페이지 타이틀 변경, 로그인 실패시 리로드, 로컬 저장 정보 변경 등
  src/component/accodion/accodion.js
  src/component/accodion/countAccodionItems.js
  src/component/addShoppingBasket/addShoppingBasket.js
  src/component/assets/_accodion.scss
  src/component/assets/_addShoppingBasket.scss
  src/component/assets/_login.scss
  src/pages/login/index.html
  src/pages/login/login.js
  src/pages/productList/index.html
  src/pages/productList/productList.js
Labels: 🔧bug, 🚀 enhancement, ⌨️ documentation, 🛠️ javascript

#236 feat: 이미지 파일 변경
  index.html
  public/images/background-title.webp
  public/images/checkpoint.png
  public/images/icon-footer.webp
  public/images/icon-header.webp
  public/images/jjolmeon-detail-info.png
  public/images/jjolmeon.png
  public/images/kurly-popup.webp
  public/images/line-banner.webp
  public/images/pagination-sprite.webp
  public/images/to-top.webp
  src/component/assets/_common.scss
  src/styles/style.scss
Labels: 🚀 enhancement

#237 refactor: console.log 제거
  src/pages/product/productCount.js
  src/pages/product/productDetail.js
Labels: 🔧bug

#234 feat : 장바구니 일부 기능 추가 및 디버깅
  src/component/assets/_cart.scss
  src/component/assets/_popup.scss
  src/pages/cart/countedItem.js
  src/pages/cart/delete.js
  src/pages/cart/index.html
  src/pages/cart/main.js
  src/pages/cart/updatePrice.js
Labels: 🛟 markup, 🎀 sass, 💡 feature, 🔧bug, 🚀 enhancement

#240 refactor: 이미지 alt 추가
  src/component/assets/_accodion.scss
  src/component/assets/_product-list.scss
  src/pages/productList/productList.js
Labels: 🚀 enhancement

#241 bug: 버블 문제 해결
  index.html
  src/pages/product/addToCartBubble.js
Labels: 🔧bug

#244 bug: 버블 미노출 오류 해결
  src/component/assets/_products-detail.scss
  src/component/assets/_products.scss
  src/pages/product/addToCartBubble.js
  src/pages/product/product-detail.html
  src/pages/product/productCount.js
Labels: 🔧bug

#245 refactor: 배너 이미지 포켓베이스 함수 추가
  index.html
  src/component/banner/banner.js
Labels: 🚀 enhancement, ⚙️ pocketbase, 🛠️ javascript

#248 refactor: 접근성 개선
  src/component/assets/_header.scss
  src/component/banner/banner.js
  src/pages/register/index.html
Labels: 🚀 enhancement

#247 feat : 아코디언 펼치기
  src/component/assets/_cart.scss
  src/pages/cart/main.js
Labels: 🚀 enhancement

#250 feat : 장바구니 갯수 추가
  public/images/icon-footer.png
  public/images/icon-header.png
  public/images/to-top.png
  src/component/assets/_header.scss
  src/component/assets/_mypage.scss
  src/component/header/header.js
  src/component/product/product-slide.js
  src/component/recent-product/main.js
  src/lib/dom/CustomSwiper.js
  src/lib/dom/getCartData.js
  src/lib/dom/index.js
  src/pages/member/mypage.js
Labels: 🚀 enhancement

#252 feat: 신상품 페이지만 다른 DB로 랜더링하기
  src/component/addShoppingBasket/addShoppingBasket.js
  src/pages/productList/productList.js
Labels: 💡 feature, 🚀 enhancement, 🛠️ javascript

#254 refactor : 마이페이지 이미지 둥글게
  src/component/assets/_mypage.scss
Labels: 🚀 enhancement

#256 fix: 페이지 이동 시 장바구니 팝업 생성 불가로 인한 코드 복구
  src/component/addShoppingBasket/addShoppingBasket.js
  src/pages/productList/productList.js
Labels: 🔧bug, 🛠️ javascript

#257 feat: SEO 개선
  index.html
  robots.txt
  src/component/banner/banner.html
  src/component/cancel/cancel.js
  src/component/footer/footer.js
  src/component/header/header.js
  src/pages/cart/index.html
  src/pages/login/index.html
  src/pages/member/mypage.html
  src/pages/product/product-detail.html
  src/pages/productList/index.html
  src/pages/register/index.html
Labels: 🚀 enhancement

#259 feat : 카테고리 UI 삭제 기능 추가
  src/pages/cart/delete.js
  src/pages/cart/main.js
Labels: 💡 feature, 🚀 enhancement

#261 fix : 배송아이콘 이미지 webp로 수정
  src/component/assets/_cart.scss
Labels: 🎀 sass

#262 refactor : product slide
  src/component/assets/_header.scss
  src/component/assets/_products-slide.scss
  src/component/product/product-slide.js
Labels: 💡 feature, 🚀 enhancement

#264 feat : 장바구니에 삭제시 장바구니 카운터 감소
  src/pages/cart/delete.js
Labels: 💡 feature

#265 feat: 퍼포먼스 개선
  src/component/assets/_mypage.scss
  src/lib/dom/CustomSwiper.js
  src/lib/dom/closeCartPopUp.js
  src/lib/dom/openCartPopUp.js
  src/lib/dom/recentProducts.js
  src/lib/dom/renderProductItem.js
  src/pages/register/index.html
Labels: 🔧bug, 🚀 enhancement

#268 docs: 7/18일 작업내용 작성
  README.md
Labels: ⌨️ documentation

#269 docs : 리드미 추가
  README.md
Labels: ⌨️ documentation

#271 feat: 접근성을 위한 키보드로 팝업 접근시 바로 접근 가능하도록 변경
  README.md
  src/component/addShoppingBasket/addShoppingBasket.js
Labels: 🚀 enhancement, 🛠️ javascript

#274 feat : 메인페이지 키보드 접근성 향상 및 불필요한 파일 제거 및 함수 분리
  README.md
  index.html
  src/component/assets/_header.scss
  src/component/header/header.js
  src/component/product/product-slide.js
  src/component/product/product-slide2.js
  src/component/product/test.js
  src/lib/dom/getId.js
  src/lib/dom/getUrl.js
  src/lib/dom/index.js
  src/pages/main/CustomSwiper.js
  src/pages/main/index.js
  src/pages/main/recentProducts.js
  src/pages/main/removeRecentProducts.js
  src/pages/main/renderProductItem.js
Labels: 💡 feature, 🚀 enhancement, 🛠️ javascript

#275 feat : 배송비 무료조건 추가
  src/component/assets/_cart.scss
  src/pages/cart/countedItem.js
  src/pages/cart/delete.js
  src/pages/cart/hidePrice.js
  src/pages/cart/index.html
  src/pages/cart/sumAllPrice.js
  src/pages/cart/updatePrice.js
Labels: 🚀 enhancement, 🛠️ javascript

#276 fix : header.scss 현재 주소 없을때 나오는 선 제거
  src/component/assets/_header.scss
Labels: 🎀 sass
